#!/bin/bash

function main {
  case "$1" in
  pack*)
    package 'initramfs.cpio'
    ;;
  get*)
    getbusybox "$2"
    ;;
  esac
}

function package (
  cd rootfs
  find . -print0 | cpio --null --create --format=newc
) > "$1"

function getbusybox {
  case "$1" in
  arm)
    curl -L 'http://mirror.archlinuxarm.org/armv6h/community/busybox-1.34.1-1-armv6h.pkg.tar.xz' \
      | tar --extract --xz --strip-components 2 'usr/bin/busybox' ;;
  aarch)
    curl -L 'http://mirror.archlinuxarm.org/aarch64/community/busybox-1.34.1-1-aarch64.pkg.tar.xz' \
      | tar --extract --xz --strip-components 2 'usr/bin/busybox' ;;
  esac
}

function package (
  cd rootfs
  find . -print0 | cpio --null --create --format=newc
) > "$1"

main "$@"
