#!/bin/bash

# https://archlinux.org/packages/community/x86_64/busybox/download
# http://mirror.archlinuxarm.org/armv6h/community/busybox-1.34.1-1-armv6h.pkg.tar.xz

function getbusybox (
  local url="$1"
# curl --location "$url" | tar --extract --xz   --strip-components 2 'usr/bin/busybox'
  curl --location "$url" | tar --extract --zstd --strip-components 2 'usr/bin/busybox'
)

function package (
  local target="$1"

  rm -f "$target"

  if [ ! -f 'rootfs/bin/busybox' ]; then
    getbusybox 'https://archlinux.org/packages/community/x86_64/busybox/download'
    mv 'busybox' 'rootfs/bin/'
  fi

  cd rootfs
  find . -print0 | cpio --null --create --format=newc | gzip --best > "../$target"
)

function start {
  qemu-system-x86_64 -initrd ./initramfs.cpio.gz -kernel /boot/vmlinuz-linux-lts -nographic -curses
}

function main {
  case "$1" in
  package)
    package 'initramfs.cpio.gz'
    ;;
  launch)
    termite -e "$0"
    ;;
  *)
    start
    ;;
  esac
}

main "$@"

