#!/bin/bash

function getbusybox {
  case "$1" in
  armv)
    curl -L 'http://mirror.archlinuxarm.org/armv6h/community/busybox-1.34.1-1-armv6h.pkg.tar.xz' \
      | tar --extract --xz --strip-components 2 'usr/bin/busybox' ;;
  x86)
    curl -L 'https://archlinux.org/packages/community/x86_64/busybox/download' \
      | tar --extract --zstd --strip-components 2 'usr/bin/busybox' ;;
  esac
}

function package {
  ( cd rootfs
    find . -print0 | cpio --null --create --format=newc | gzip --best
  ) > "$1"
}


function start {
  qemu-system-x86_64 -initrd ./initramfs.cpio.gz -kernel /boot/vmlinuz-linux-lts -nographic -curses
}

function main {
  case "$1" in
  package)
    package 'initramfs.cpio.gz'
    ;;
  launch)
    termite -e "$0"
    ;;
  *)
    start
    ;;
  esac
}

main "$@"
