#!/bin/busybox sh

/bin/busybox --install -s /bin

mkdir -p /proc /sys /dev

# mount important file systems
mount -t proc     none /proc
mount -t sysfs    none /sys
mount -t devtmpfs none /dev

source /etc/config

for task in /run/*.sh; do
  /bin/run $task
done

sleep 100
