#!/bin/busybox sh

/bin/busybox --install -s /bin

mkdir -p /proc /sys /dev /mnt

# mount pseudo file systems
mount -t proc     none /proc
mount -t sysfs    none /sys
mount -t devtmpfs none /dev

source /etc/config

# run available tasks
for task in /run/*.sh; do (
  source $task && main
) done

# switch root and continue init
mount /dev/mmcblk0p2 /mnt
exec switch_root /mnt /sbin/init || {
  echo 'failed to switch root'
  shell
}
